<a href="https://colab.research.google.com/github/vvinjamoori/Python/blob/main/Food_Delivery_Data_Exploration_and_analysis_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Food Delivery Data Exploration and Analysis 4

# Agenda of the lecture




* Introduction to Pandas
* Pandas Core Components - DataFrame & Series
* Zomato Bangalore dataset
* Basic Operations in rows
* Basic Operations on Columns
* Nulls
    * Unique Value
    * Value Count


# Introduction to Pandas




Pandas is a powerful library for data manipulation and analysis in Python. It builds on top of **NumPy** and provides easy-to-use data structures and functions for handling structured data.

### Why Use Pandas?
1. **Real-World Relevance**: Pandas helps analyze large datasets efficiently, such as customer reviews, financial data, or restaurant data like our **Zomato Bangalore dataset**.
2. **Core Strengths**:
   - Data cleaning, preparation, and exploration.
   - Supports handling **missing data**.
   - Integrates seamlessly with libraries like `Matplotlib` and `NumPy`.



**Installing Pandas**
To install Pandas, use the following command:

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

# Pandas Core Components - DataFrame & Series


<span style=" color: red;"> Note:</span> According to the script, this came after loading the dataset, but I felt we should introduce the concept of series and dataframe first, since they are the building blocks of pandas.

### Series
A **Series** is a one-dimensional labeled array that can hold any data type. Think of it as a **single column of data** in a table.

**Key Features for Zomato Analysis**:
- Data is labeled using an **index** (e.g., restaurant names or IDs for easy lookup).
- Supports operations like indexing, slicing, and filtering (e.g., selecting restaurants with ratings above 4.0 or costs below ₹500).


<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/169/736/original/download_%281%29.png?1765259109" width="500" />


### DataFrame
A **DataFrame** is a two-dimensional table with labeled rows and columns. It is the core structure in Pandas, ideal for tabular data like the Zomato dataset.

**Key Features for Zomato Analysis**:
- Can hold data of different types (e.g., restaurant names as strings, ratings as floats, cost_for_two as integers).
- Labeled rows (**index**, e.g., restaurant IDs) and columns (e.g., cuisine, location).
- Provides tools for filtering (e.g., restaurants in a specific area), aggregating (e.g., average rating by cuisine), and transforming data (e.g., normalizing costs).

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/169/737/original/download_%2841%29.png?1765259184" width="500" />

Creating Series from numpy arrays ( highlight that pandas is implemented using numpy)

In [ ]:
votes = np.array([120, 240, 150])
ratings = np.array([4.1, 4.5, 3.9])
restaurants = np.array(['R1', 'R2', 'R3'])

In [ ]:
votes_series = pd.Series(votes, index=['R1', 'R2', 'R3'], name='Votes')

In [ ]:
votes_series

R1    120
R2    240
R3    150
Name: Votes, dtype: int64

In [ ]:
ratings_series = pd.Series(ratings, index=['R1', 'R2', 'R3'], name='Ratings')

In [ ]:
ratings_series

R1    4.1
R2    4.5
R3    3.9
Name: Ratings, dtype: float64

Introduce how two series can be combined into a dataframe - also a chance to introduce how concat and axis work in pandas.

In [ ]:
combined_df = pd.concat([votes_series,ratings_series],axis=1)

In [ ]:
combined_df

    Votes  Ratings
R1    120      4.1
R2    240      4.5
R3    150      3.9

Showcase how a dataframe can be created using a dictionary.

<span style="color: red;"> Note:</span> this part is shifted to the beginning to avoid breaking the flow from our original dataset later on.

In [ ]:
data = {
    "Restaurant": ["R1", "R2", "R3"],
    "Votes": [120, 240, 150],
    "Rating": [4.1, 4.5, 3.9]
}
df = pd.DataFrame(data)

In [ ]:
df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9

# Combining DataFrames in Pandas


# Question
When using `pd.concat([df1, df2], axis=1)`, which of the following is true if indexes do not match?

# Choices
- [ ] Pandas throws an error
- [x] Pandas aligns rows by index and introduces NaNs where missing
- [ ] Pandas ignores indexes and concatenates row-wise sequentially
- [ ] Pandas resets the index automatically


Explanation: When using `pd.concat([df1, df2], axis=1)`, Pandas performs a column-wise concatenation. If the indexes of `df1` and `df2` don’t match, Pandas aligns them based on their index labels. Wherever a label exists in one DataFrame but not in the other, Pandas fills the missing values with NaN.


# Zomato Bangalore dataset


Let's load our Zomato Bangalore dataset.

In [ ]:
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
!unzip zomato_dataset.zip
!mv zomato_dataset.csv.

--2026-01-10 16:02:02--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 18.164.173.18, 18.164.173.58, 18.164.173.117, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|18.164.173.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72602133 (69M) [application/zip]
Saving to: ‘zomato_dataset.zip’

zomato_dataset.zip  100%[===================>]  69.24M  13.6MB/s    in 6.4s

2026-01-10 16:02:09 (10.8 MB/s) - ‘zomato_dataset.zip’ saved [72602133/72602133]

Archive:  zomato_dataset.zip
  inflating: zomato_dataset.csv
mv: missing destination file operand after 'zomato_dataset.csv.'
Try 'mv --help' for more information.

In [ ]:
import pandas as pd
df = pd.read_csv('zomato_dataset.csv')

## Introduce head and tail as ways to get a quick glance at the data

To get a quick glance at the Zomato Bangalore dataset, we can use the .head() and .tail() methods. These functions help Zomato's data team understand the dataset's structure, such as column names and sample values, without loading the entire dataset.

<span style="background-color: red;"> **[Note to Instructor]:** </span>
> Turn on location if planning to showcase the links.

In [ ]:
# What key attributes (e.g., name, rating, cost) do the first and last five restaurants in the
# Zomato Bangalore dataset reveal for performance analysis?

# Let's look at the first few rows to understand the structure
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [ ]:
df.tail()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
23188,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Izakaya Gastro Pub,Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",'1200.0',"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield
23189,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,'2000.0',"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield
23190,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",Keys Cafe - Keys Hotel,No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",'1200.0',"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield
23191,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield
23192,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,'2500.0',"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield

- Use `.head()` to preview the top 5 rows of the dataset.
- Use `.head(n)` to preview the top n rows of the dataset.
- Use `.tail(n)` to preview the bottom n rows of the dataset.

### Business Context for Zomato:

- Using .head() helps Zomato's team quickly identify key columns (e.g., restaurant_name, rating, cost_for_two) and spot sample data, such as top-rated restaurants in Bangalore.
- .tail() ensures the dataset is complete by checking the last entries, which might reveal data entry issues or trends in newer restaurant listings.
These previews are critical for initial data exploration, enabling Zomato to assess data quality before analyzing customer preferences or restaurant performance.


# Basic Operations in rows


We can explore or get a feel for our dataset using loc and iloc as well.


## Slicing Rows

Rows can be sliced using implicit or explicit indices. Pandas provides two key tools for slicing:

1. **`.iloc`**: Slicing based on implicit integer indices.
2. **`.loc`**: Slicing based on explicit indices.

>[Interactive]: Explore how pandas indexing works step by step before diving into the code:
[Pandas Indexing Visualizer](https://aiml-v-izs.vercel.app/v/zb-p4m2v7c8/pd-indexing)

**Slicing Rows with `.iloc`**

Use `.iloc` for row selection by integer position:

In [ ]:
df.iloc[0]   # Access the first row

url                            https://www.zomato.com/bangalore/jalsa-banasha...
address                        942, 21st Main Road, 2nd Stage, Banashankari, ...
name                                                                       Jalsa
online_order                                                                 Yes
book_table                                                                   Yes
rate                                                                       4.1/5
votes                                                                        775
phone                                             080 42297555\r\n+91 9743772233
location                                                            Banashankari
rest_type                                                          Casual Dining
dish_liked                     Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
cuisines                                          North Indian, Mughlai, Chinese
approx_cost(for two people)                                              '800.0'
reviews_list                   [('Rated 4.0', 'RATED\n  A beautiful place to ...
menu_item                                                                     []
listed_in(type)                                                           Buffet
listed_in(city)                                                     Banashankari
Name: 0, dtype: object

In [ ]:
df.iloc[1:4]

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari

In [ ]:
# How can Zomato's data team sample every third restaurant from the second to the ninth entry in the
# Bangalore dataset to explore a subset of restaurant data?
df.iloc[1:9:3]

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
7,https://www.zomato.com/bangalore/penthouse-caf...,"1, 30th Main Road, 3rd Stage, Banashankari, Ba...",Penthouse Cafe,Yes,No,4.0/5,324,+91 8884135549\r\n+91 9449449316,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",'700.0',"[('Rated 3.0', ""RATED\n I had been to this pl...",[],Cafes,Banashankari

### Zomato Business Context:

- Using .iloc[0] helps Zomato inspect the first restaurant in the dataset (e.g., to verify data like name, rating, or cost_for_two).
- Slicing with .iloc[1:4] allows quick checks of a small group of restaurants, useful for spot-checking data quality or trends in Bangalore.
- Non-consecutive slicing (e.g., .iloc[1:9:3]) enables sampling restaurants at intervals, aiding in exploratory analysis of diverse dataset segments.


## Understanding Index in a DataFrame

Every row in a DataFrame has an **index**, which uniquely identifies the row.

Indexing is critical for:
1. Accessing specific rows.
2. Slicing multiple rows.
3. Efficient filtering and data manipulation.

**Key Types of Indexing:**
1. **Implicit Index**: The default integer-based row indices (`0, 1, 2, ...`).
2. **Explicit Index**: Custom labels you assign to rows (e.g., names or IDs).

In [ ]:
# How can Zomato's data team set name as the explicit index in the
# Bangalore dataset to facilitate quick lookups and analysis of specific restaurants?

df_explicit = df.set_index("name")
df_explicit

,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
name,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
Spice Elephant,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
San Churro Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
Addhuri Udupi Bhojana,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
Grand Village,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Izakaya Gastro Pub,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",'1200.0',"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield
M Bar - Bengaluru Marriott Hotel Whitefield,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,'2000.0',"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield
Keys Cafe - Keys Hotel,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",'1200.0',"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield
Bhagini,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield
Chime - Sheraton Grand Bengaluru Whitefield Hotel &...,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,'2500.0',"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield

### Zomato Business Context:

- Setting `name` (restaurant name) as the explicit index allows Zomato’s data team to quickly look up and analyze specific restaurants without scanning the entire dataset. For example, analysts can instantly retrieve details like ratings, cuisines, or average cost for a restaurant such as “Jalsa” or “Tuk-Tuk”.

- An explicit index on restaurant names simplifies filtering, comparison, and grouping tasks, such as analyzing performance of the same restaurant across different areas in Bangalore or tracking changes in ratings over time. This improves efficiency in restaurant recommendation systems, operational insights, and targeted marketing campaigns.


## Use .loc to access rows based on index

In [ ]:
df_explicit.loc["Jalsa"]

,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
name,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\r\r\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Dine-out,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1 /5,804,080 42297555\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Paneer Lajawab, Masala Pa...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n Super ambience\nGreat...",[],Dine-out,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-maratha...,"25/7, Doddannakundi, Outer Ring Road, Mahadeva...",Yes,Yes,4.2/5,2173,+91 7406617555\r\n+91 7406627555,Marathahalli,Casual Dining,"Mutton Curry, Stuffed Mushroom, Laccha Paratha...","North Indian, Mughlai",'1500.0',"[('Rated 4.0', 'RATED\n A pretty decent place...",[],Delivery,Brookefield
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1 /5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Dine-out,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-maratha...,"25/7, Doddannakundi, Outer Ring Road, Mahadeva...",Yes,Yes,4.2 /5,2189,+91 7406617555\n+91 7406627555,Marathahalli,Casual Dining,"Mutton Curry, Stuffed Mushroom, Laccha Paratha...","North Indian, Mughlai",'1500.0',"[('Rated 4.0', 'RATED\n Friendly staff, avera...",[],Delivery,Marathahalli

You can also select multiple indices using loc.

In [ ]:
df_explicit.loc[["Jalsa", "Tuk-Tuk"]]

,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
name,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\r\r\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Dine-out,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1 /5,804,080 42297555\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Paneer Lajawab, Masala Pa...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n Super ambience\nGreat...",[],Dine-out,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-maratha...,"25/7, Doddannakundi, Outer Ring Road, Mahadeva...",Yes,Yes,4.2/5,2173,+91 7406617555\r\n+91 7406627555,Marathahalli,Casual Dining,"Mutton Curry, Stuffed Mushroom, Laccha Paratha...","North Indian, Mughlai",'1500.0',"[('Rated 4.0', 'RATED\n A pretty decent place...",[],Delivery,Brookefield
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1 /5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Dine-out,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-maratha...,"25/7, Doddannakundi, Outer Ring Road, Mahadeva...",Yes,Yes,4.2 /5,2189,+91 7406617555\n+91 7406627555,Marathahalli,Casual Dining,"Mutton Curry, Stuffed Mushroom, Laccha Paratha...","North Indian, Mughlai",'1500.0',"[('Rated 4.0', 'RATED\n Friendly staff, avera...",[],Delivery,Marathahalli
Tuk-Tuk,https://www.zomato.com/bangalore/tuk-tuk-white...,"2nd Floor, Food Court, VR Mall, Whitefield, Ba...",No,No,2.7 /5,36,+91 8105882336,Whitefield,Food Court,Biryani,North Indian,'400.0',"[('Rated 4.0', ""RATED\n I like this place bec...",[],Dine-out,Whitefield

You can also reset the index to get back the original df.

In [ ]:
df_explicit.reset_index()

,name,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,Spice Elephant,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,San Churro Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,Addhuri Udupi Bhojana,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,Grand Village,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",'1200.0',"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,'2000.0',"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",'1200.0',"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield
23191,Bhagini,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,'2500.0',"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield

### Zomato Business Context:

- Resetting the index to implicit integers (0, 1, 2, ...) simplifies row-based operations, such as slicing or iterating over restaurants, which is useful for Zomato’s data team when analyzing large datasets.
- Using drop=True prevents clutter from unnecessary columns (e.g., old restaurant names as index), keeping the dataset clean for tasks like generating reports or feeding data into recommendation algorithms.
- The inplace=True option optimizes memory usage by updating the DataFrame directly, crucial for handling large restaurant datasets efficiently in Zomato’s analytics pipeline.

We can drop the index altogether.

In [ ]:
df_explicit.reset_index(drop=True)

,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",'1200.0',"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield
23189,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,'2000.0',"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield
23190,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",'1200.0',"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield
23191,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield
23192,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,'2500.0',"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield

## Introducing inplace

In [ ]:
df_explicit.reset_index(inplace=True)

## Introduce .info() as a way to understand what columns are there, how many non-nulls, datatypes, and memory usage


<span style="color: violet;">Q. How can Zomato's data team quickly inspect the structure, column names, data types, and missing values of the Bangalore restaurant dataset to ensure its quality for analyzing restaurant performance and customer preferences?</span>

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          23193 non-null  object
 1   address                      23193 non-null  object
 2   name                         23193 non-null  object
 3   online_order                 23193 non-null  object
 4   book_table                   23193 non-null  object
 5   rate                         23193 non-null  object
 6   votes                        23193 non-null  int64
 7   phone                        23193 non-null  object
 8   location                     23193 non-null  object
 9   rest_type                    23193 non-null  object
 10  dish_liked                   23193 non-null  object
 11  cuisines                     23193 non-null  object
 12  approx_cost(for two people)  23193 non-null  object
 13  reviews_list                 23193 non-null  object
 14  menu_item                    23193 non-null  object
 15  listed_in(type)              23193 non-null  object
 16  listed_in(city)              23193 non-null  object
dtypes: int64(1), object(16)
memory usage: 3.0+ MB

`df.info()` gives a list of columns with:

- **Name** of columns
- **How many non-null values (blank cells)** each column has - observe location has a few nulls, which we will see how to handle later
- **Type of values** in each column - int, float, etc.

**By default**, it shows **Dtype** as `object` for anything other than **int or float**.


### Zomato Business Context:

- Knowing which columns have missing values (e.g., incomplete rating data) helps Zomato prioritize data cleaning for accurate recommendations.
- Identifying data types ensures proper handling (e.g., cost_for_two as numeric for cost analysis or rating as float for averaging).
- Memory usage insights guide Zomato in optimizing large datasets for performance in their analytics pipeline.

## Introduce. .describe(), which can give a quick statistical view of the data


<span style="color: violet;">Q. How can Zomato's data team obtain a statistical summary of numerical columns like ratings or costs in the Bangalore restaurant dataset to identify trends in restaurant performance?</span>

In [ ]:
df.describe()

              votes
count  23193.000000
mean     601.074462
std     1114.854301
min        0.000000
25%      101.000000
50%      221.000000
75%      586.000000
max    16832.000000

Observe that we are getting statistical info of only 1 column. Why? Because all other columns are in object form. We will need to typecast some of our columns to convert them into numeric forms.

### Zomato Business Context:

- .describe() reveals key metrics, such as the average rating or cost_for_two across Bangalore restaurants, helping Zomato identify top-performing restaurants or typical dining costs for user recommendations.
- It highlights outliers (e.g., restaurants with unusually high costs or low ratings), which can guide Zomato’s restaurant success team in offering targeted support to improve performance.
- If only a few columns appear in the output (e.g., rating but not cost_for_two), it indicates non-numeric columns (stored as objects) may need typecasting to numeric for deeper analysis, such as calculating average costs or vote counts.
- These insights empower Zomato to optimize marketing campaigns, refine restaurant recommendations, or assist partners in adjusting pricing or improving service quality based on statistical trends


# Row operations in Pandas

# Question
If we do `df.iloc[0]`, what is returned?
# Choices
- [ ] A DataFrame containing the first row
- [x] A Series representing the first row
- [ ] A NumPy array with values from the first row
- [ ] A tuple with index and values

Explanation:

- `iloc` is purely positional indexing.


- `df.iloc[0]` fetches the first row (since Python indexing starts at $0$).


- The result is a Pandas Series, where:


    - The index of the Series corresponds to the DataFrame’s columns.


    - The values are the entries in that row.


# Basic Operations on Columns


Columns in a Pandas DataFrame represent individual data features.

Columns named approx_cost(for two people) and rating are in object type when they are supposed to be in float/int form.

## Accessing Columns

You can access columns using:
- **Dot notation**: `df.column_name`  
- **Bracket notation**: `df["column_name"]`

<span style="color: violet;">Q. How can Zomato's data team retrieve the approx_cost(for two people) column from the Bangalore restaurant dataset to study dining cost patterns?</span>

In [ ]:
# Accessing columns
costs = df["approx_cost(for two people)"]  # Bracket notation
print(costs)

0         '800.0'
1         '800.0'
2         '800.0'
3         '300.0'
4         '600.0'
           ...
23188    '1200.0'
23189    '2000.0'
23190    '1200.0'
23191     '800.0'
23192    '2500.0'
Name: approx_cost(for two people), Length: 23193, dtype: object

In [ ]:
rating = df.rate  # Dot notation
print(rating)

0         4.1/5
1         4.1/5
2         3.8/5
3         3.7/5
4         3.8/5
          ...
23188    3.8 /5
23189    3.9 /5
23190    2.8 /5
23191    2.5 /5
23192    4.3 /5
Name: rate, Length: 23193, dtype: object

In [ ]:
df[['approx_cost(for two people)', 'rate' ]]  #accessing multiple columns

      approx_cost(for two people)    rate
0                         '800.0'   4.1/5
1                         '800.0'   4.1/5
2                         '800.0'   3.8/5
3                         '300.0'   3.7/5
4                         '600.0'   3.8/5
...                           ...     ...
23188                    '1200.0'  3.8 /5
23189                    '2000.0'  3.9 /5
23190                    '1200.0'  2.8 /5
23191                     '800.0'  2.5 /5
23192                    '2500.0'  4.3 /5

[23193 rows x 2 columns]

### Zomato Business Context:

- Accessing the approx_cost(for two people) column helps Zomato analyze pricing trends across Bangalore restaurants.
- The rate column provides customer satisfaction scores, essential for recommending top-rated spots.

## Renaming Columns
Use the df.rename() function to rename columns.

The Column named approx_cost(for two people) can be renamed to something shorter, and rate can be renamed to rating.

<span style="color: violet;">Q. How can Zomato's data team rename the approx_cost(for two people), votes, and rate columns to cost_for_two, Total_Votes and Ratings in the Bangalore restaurant dataset to improve clarity for analysis?</span>

In [ ]:
# Renaming columns
df = df.rename(columns={"approx_cost(for two people)":'cost_for_two',"votes": "Total_Votes", "rate": "Ratings"})

# Displaying renamed DataFrame
df.head()

,url,address,name,online_order,book_table,Ratings,Total_Votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

### Zomato Business Context:

- Renaming approx_cost(for two people) to cost_for_two simplifies queries for pricing analysis, such as identifying affordable restaurants for Zomato users in Bangalore.
- Changing votes to Total_Votes clearly indicates customer engagement (number of reviews), aiding in ranking restaurant popularity.
- Renaming rate to Ratings ensures consistency for customer satisfaction metrics, making it easier to analyze and visualize restaurant performance for Zomato’s recommendation engine or marketing campaigns.


**Key Point**: Renaming ensures clarity, especially when column names are too short or unclear or have some formatting errors.

## Adding a New Column
Add a new column by assigning data to a new column name.

Let's transform ratings into the required form.

In [ ]:
# Adding a new column
df["only_rating"] = df["Ratings"].str[:-2]

# Displaying a new column
df["only_rating"]

0         4.1
1         4.1
2         3.8
3         3.7
4         3.8
         ...
23188    3.8
23189    3.9
23190    2.8
23191    2.5
23192    4.3
Name: only_rating, Length: 23193, dtype: object

As you can see, the rating is still in object type. We need to convert it into a float type.

In [ ]:
# It is expected to fail!
df["only_rating"] = df["only_rating"].astype(float)

ValueError: could not convert string to float: 'N'

<span style="color: violet;">It is failing because it looks like there is an 'N' in the ratings column, which cannot be converted into a float. What are our options?</span>

### Option 1

**Replacing certain values in object type columns**

In [ ]:
df["only_rating"] = df["only_rating"].replace('N', np.nan)

In [ ]:
df["only_rating"] = df["only_rating"].astype(float)

It is now working

### Option 2

**Use pd.to_numeric with errors='coerce'**

pd.to_numeric converts a column into a numeric type. Errors = 'coerce' is a parameter that will force the operation and convert values it cannot handle into nulls.

In [ ]:
df["only_rating"] = pd.to_numeric(df["only_rating"], errors='coerce')

In [ ]:
df["only_rating"]

0        4.1
1        4.1
2        3.8
3        3.7
4        3.8
        ...
23188    3.8
23189    3.9
23190    2.8
23191    2.5
23192    4.3
Name: only_rating, Length: 23193, dtype: float64

In [ ]:
df["cost_for_two"]

0         '800.0'
1         '800.0'
2         '800.0'
3         '300.0'
4         '600.0'
           ...
23188    '1200.0'
23189    '2000.0'
23190    '1200.0'
23191     '800.0'
23192    '2500.0'
Name: cost_for_two, Length: 23193, dtype: object

In [ ]:
df["cost_for_two"] = pd.to_numeric(df["cost_for_two"].str.strip("'\""), errors="coerce")

In [ ]:
df["cost_for_two"]

0         800.0
1         800.0
2         800.0
3         300.0
4         600.0
          ...
23188    1200.0
23189    2000.0
23190    1200.0
23191     800.0
23192    2500.0
Name: cost_for_two, Length: 23193, dtype: float64

In [ ]:
# Adding a new column
df['cost_for_one']  = df['cost_for_two'] / 2

# Displaying a new column
df['cost_for_one']

0         400.0
1         400.0
2         400.0
3         150.0
4         300.0
          ...
23188     600.0
23189    1000.0
23190     600.0
23191     400.0
23192    1250.0
Name: cost_for_one, Length: 23193, dtype: float64

In [ ]:
df["is_good"] = df["only_rating"] > 4
df["is_good"]

0         True
1         True
2        False
3        False
4        False
         ...
23188    False
23189    False
23190    False
23191    False
23192     True
Name: is_good, Length: 23193, dtype: bool

# Some other function in pandas

# Question
Which of the following statements about df.rename() is TRUE?
# Choices
- [ ] `df.rename(columns={"A": "B"})` will throw an error if column "A" does not exist
- [ ] `df.rename(columns={"A": "B"})` renames column "A" to "B" and modifies df permanently
- [x] `df.rename(columns={"A": "B"})` returns a new DataFrame by default
- [ ] `df.rename("A", "B")` is a valid syntax for renaming a column

Explanation :
A) ❌ False → `df.rename(columns={"A": "B"})` will not throw an error if "A" doesn’t exist. Pandas just ignores it silently.

B) ❌ False → By default, `rename()` does not modify df permanently. You’d need `inplace=True` for that.

C) ✅ True → Yes — without `inplace=True`, it returns a new DataFrame with renamed labels.

D) ❌ False → `df.rename("A", "B")` is invalid syntax. You must specify `columns={"old": "new"}` (for columns) or `index={old: new}` (for rows).


# Unique Value and Value Count



## Unique Values in a Column

The `df["column_name"].unique()` method lists unique values in a column.

> [Interactive]: See how unique values and value counts are computed step by step before diving into the code: [Unique & Value Counts Visualizer](https://aiml-v-izs.vercel.app/v/zb-p4m2v7c8/pd-columns)
Select Unique from dropdown.

<span style=" color: red;">Narrative:</span> you want to see which locations and the number of unique locations these restaurants belong to.

In [ ]:
# Finding unique values in the 'location' column
unique_locations = df["location"].unique()
print(unique_locations)

['Banashankari' 'Basavanagudi' 'Jayanagar' 'Kumaraswamy Layout'
 'Rajarajeshwari Nagar' 'Mysore Road' 'Uttarahalli' 'South Bangalore'
 'Vijay Nagar' 'Bannerghatta Road' 'JP Nagar' 'BTM' 'Wilson Garden'
 'Koramangala 5th Block' 'Shanti Nagar' 'Richmond Road' 'City Market'
 'Bellandur' 'Sarjapur Road' 'Marathahalli' 'HSR' 'Old Airport Road'
 'Indiranagar' 'Koramangala 1st Block' 'East Bangalore' 'MG Road'
 'Brigade Road' 'Lavelle Road' 'Church Street' 'Ulsoor' 'Residency Road'
 'Shivajinagar' 'Infantry Road' 'St. Marks Road' 'Cunningham Road'
 'Race Course Road' 'Domlur' 'Koramangala 8th Block' 'Frazer Town'
 'Ejipura' 'Vasanth Nagar' 'Jeevan Bhima Nagar' 'Old Madras Road'
 'Commercial Street' 'Koramangala 6th Block' 'Majestic' 'Langford Town'
 'Koramangala 7th Block' 'Brookefield' 'Whitefield'
 'ITPL Main Road, Whitefield' 'Varthur Main Road, Whitefield'
 'Koramangala 2nd Block' 'Koramangala 3rd Block' 'Koramangala 4th Block'
 'Koramangala' 'Bommanahalli' 'Hosur Road' 'Seshadripuram'
 'Electronic City' 'Banaswadi' 'North Bangalore' 'RT Nagar' 'Kammanahalli'
 'Hennur' 'HBR Layout' 'Kalyan Nagar' 'Thippasandra' 'CV Raman Nagar'
 'Kaggadasapura' 'Kanakapura Road' 'Nagawara' 'Rammurthy Nagar'
 'Sankey Road' 'Central Bangalore' 'Malleshwaram' 'Sadashiv Nagar'
 'Basaveshwara Nagar' 'Rajajinagar' 'New BEL Road' 'West Bangalore'
 'Yeshwantpur' 'Sanjay Nagar' 'Sahakara Nagar' 'Jalahalli' 'Yelahanka'
 'Magadi Road' 'KR Puram']

The `df["column_name"].nunique()` method lists the number of unique values in a column.

In [ ]:
number_of_unique_locations = df["location"].nunique()
print(number_of_unique_locations)

88

## Value Counts in a Column

The `df["column_name"].value_counts()` method counts occurrences of each unique value.

> [Interactive]: See how unique values and value counts are computed step by step before diving into the code: [Unique & Value Counts Visualizer](https://aiml-v-izs.vercel.app/v/zb-p4m2v7c8/pd-columns)
Select Value Counts from dropdown.

<span style="color: red;">Narrative:</span> you might want to find out which are the most popular locations that people order from/ dine in

In [ ]:
# How can Zomato's data team count the number of restaurants in each unique location in the
# Bangalore dataset to identify the most popular dining or ordering areas?


# Counting occurrences of each unique value
location_counts = df["location"].value_counts()
location_counts

location
Koramangala 5th Block    1783
BTM                      1456
Indiranagar              1350
HSR                      1162
Jayanagar                1037
                         ...
Kanakapura Road             2
West Bangalore              2
Yelahanka                   2
Magadi Road                 2
KR Puram                    1
Name: count, Length: 88, dtype: int64

<span style="color: violet;">Question: Which is the most ordered restaurant in the dataset?</span>

In [ ]:
restaurant_order_counts = df["name"].value_counts()
restaurant_order_counts

name
Onesta               85
Empire Restaurant    69
KFC                  59
McDonald's           57
Pizza Hut            56
                     ..
Bao & Grills          1
Gongura               1
Tuk-Tuk               1
Karibu - The Zuri     1
Fujian Express        1
Name: count, Length: 3159, dtype: int64

<span style="color: violet;">Which type of listing (e.g., delivery, dine-out, etc.) is the most common?</span>

In [ ]:
listing_counts = df['listed_in(type)'].value_counts()
listing_counts

listed_in(type)
Delivery              10625
Dine-out               8009
Desserts               1333
Cafes                  1047
Drinks & nightlife      890
Buffet                  762
Pubs and bars           527
Name: count, dtype: int64

### Zomato Business Context:

- Location Counts: High counts for locations like Koramangala or Indiranagar indicate demand hotspots, allowing Zomato to allocate more delivery riders or target promotions in these areas.
- Restaurant Orders: Identifying the most ordered restaurants (e.g., a chain appearing frequently) helps Zomato prioritize partnerships, feature them in promotions, or include them in loyalty programs like Zomato Gold.
- Listing Types: A dominance of delivery listings suggests a preference for online orders, guiding Zomato to enhance delivery logistics or focus app features on delivery options over dine-out in Bangalore.

We are exporting the dataset now and we’ll contiue to work with it in the next lecture

In [ ]:
df.to_csv('zomato_dataset.csv', index=False)

https://drive.google.com/file/d/1i-tHRLBGkq_X2BHrJtiRNMLA4AZCCzZc/view?usp=sharing